# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    meta.helm.sh/release-name: stable
    meta.helm.sh/release-namespace: prometheus
  creationTimestamp: "2024-05-07T15:00:24Z"
  generation: 2
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: stable
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 58.1.1
    chart: kube-prometheus-stack-58.1.1
    heritage: Helm
    release: stable
  name: stable-kube-prometheus-sta-prometheus
  namespace: prometheus
  resourceVersion: "3306508"
  uid: 80ac942d-7a12-4040-b4b2-aace86e0714c
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: stable-kube-prometheus-sta-alertmanager
      namespace: prometheus
      pathPrefix: /
      port: http-web
  enableAdminAPI: false
  evaluationInterval: 30s
  externalUrl: http://kube.eta2u.demo/prometheus
  hostNetwork: false
  image: quay.io/prometheus/prometheus:v2.51.2
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: stable
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: stable
  replicas: 1
  retention: 10d
  routePrefix: /prometheus
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: stable
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector:
    matchLabels:
      release: stable
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: stable-kube-prometheus-sta-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: stable
  shards: 1
  tsdb:
    outOfOrderTimeWindow: 0s
  version: v2.51.2
  walCompression: true
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-05-08T10:27:45Z"
    message: ""
    observedGeneration: 2
    reason: ""
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-08T10:27:45Z"
    message: ""
    observedGeneration: 2
    reason: ""
    status: "True"
    type: Reconciled
  paused: false
  replicas: 1
  selector: app.kubernetes.io/instance=stable-kube-prometheus-sta-prometheus,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,operator.prometheus.io/name=stable-kube-prometheus-sta-prometheus,prometheus=stable-kube-prometheus-sta-prometheus
  shardStatuses:
  - availableReplicas: 1
    replicas: 1
    shardID: "0"
    unavailableReplicas: 0
    updatedReplicas: 1
  shards: 1
  unavailableReplicas: 0
  updatedReplicas: 1
